### ISSUE TITLE
connecter le bon sellsy et pas le sellsy de test

### ISSUE THREAD

**Issue by mathieusaudel** [medialeads/rebirth_api_client#1]
pour créer une API client, il faut que dans Sellsy la date de fin d'abonnement MEI soit rempli
et en retour ça rempli le champs Token dans sellsy automatiquement.

Donc actuellement c'est branché sur le sellsy de test
donc il faut que tu le connectes sur le bon sellsy

**Comment by fancyweb** [comment]
Ce repo concerne le client API public. Et ce repo est public donc nos clés API ont été leak (j'ai édité ton message). Renouvelle les au plus vite. Et réouvre l'issue ailleurs pour le suivi. Merci.
